### ISSUE TITLE
'npm run build' not working

### ISSUE THREAD

**Issue by erikvullings** [ArthurClemens/mithril-vite-starter#1]
I didn't debug it, but `npm run dev` works like a charm, but when I used `npm run build`, and tried to serve the build folder using `http-server build`, and I try to open http://localhost:8080, it fails with the following error in the browser: `​crbug/1173575, non-JS module files deprecated.`. 

The same procedure applied to the `vanilla-ts` template does work, however. Am I doing something wrong?

**Comment by ArthurClemens** [comment]
The build folder is called "dist", so you should serve it using `http-server dist`.
